kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app":"mariadb-pipelines-definition","component":"data-science-pipelines","dspa":"pipelines-definition"},"name":"mariadb-pipelines-definition","namespace":"fraud-detection","ownerReferences":[{"apiVersion":"datasciencepipelinesapplications.opendatahub.io/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"DataSciencePipelinesApplication","name":"pipelines-definition","uid":"e9b6de73-b1cf-422e-b6c9-1ba93d900075"}]},"spec":{"selector":{"matchLabels":{"app":"mariadb-pipelines-definition","component":"data-science-pipelines","dspa":"pipelines-definition"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"mariadb-pipelines-definition","component":"data-science-pipelines","dspa":"pipelines-definition"}},"spec":{"containers":[{"env":[{"name":"MYSQL_USER","value":"mlpipeline"},{"name":"MYSQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"ds-pipeline-db-pipelines-definition"}}},{"name":"MYSQL_DATABASE","value":"mlpipeline"},{"name":"MYSQL_ALLOW_EMPTY_PASSWORD","value":"true"}],"image":"registry.redhat.io/rhel8/mariadb-103@sha256:b3a6f3fecc2629b61a8940e792e623318c46fd71585486794f6cebb76c89b5df","livenessProbe":{"failureThreshold":3,"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"tcpSocket":{"port":3306},"timeoutSeconds":1},"name":"mariadb","ports":[{"containerPort":3306}],"readinessProbe":{"exec":{"command":["/bin/sh","-i","-c","MYSQL_PWD=$MYSQL_PASSWORD
      mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT
      1'"]},"failureThreshold":3,"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":1,"memory":"1Gi"},"requests":{"cpu":"300m","memory":"800Mi"}},"volumeMounts":[{"mountPath":"/var/lib/mysql","name":"mariadb-persistent-storage"}]}],"serviceAccountName":"ds-pipelines-mariadb-sa-pipelines-definition","volumes":[{"name":"mariadb-persistent-storage","persistentVolumeClaim":{"claimName":"mariadb-pipelines-definition"}}]}}}}
    manifestival: new
  resourceVersion: '460593966'
  name: mariadb-pipelines-definition
  uid: 9e3e6798-44b0-4392-92c0-9819820b1fa9
  creationTimestamp: '2024-02-14T18:49:42Z'
  generation: 2
  managedFields:
    - manager: manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-02-14T18:49:43Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
            'f:manifestival': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:component': {}
            'f:dspa': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"e9b6de73-b1cf-422e-b6c9-1ba93d900075"}': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:component': {}
                'f:dspa': {}
            'f:spec':
              'f:volumes':
                .: {}
                'k:{"name":"mariadb-persistent-storage"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
              'f:containers':
                'k:{"name":"mariadb"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/var/lib/mysql"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:tcpSocket':
                      .: {}
                      'f:port': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    .: {}
                    'k:{"name":"MYSQL_ALLOW_EMPTY_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"MYSQL_DATABASE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"MYSQL_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"MYSQL_USER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:readinessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":3306,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:serviceAccount': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:terminationGracePeriodSeconds': {}
              'f:serviceAccountName': {}
              'f:securityContext': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-02-14T18:50:42Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: fraud-detection
  ownerReferences:
    - apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
      kind: DataSciencePipelinesApplication
      name: pipelines-definition
      uid: e9b6de73-b1cf-422e-b6c9-1ba93d900075
      controller: true
      blockOwnerDeletion: true
  labels:
    app: mariadb-pipelines-definition
    component: data-science-pipelines
    dspa: pipelines-definition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-pipelines-definition
      component: data-science-pipelines
      dspa: pipelines-definition
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb-pipelines-definition
        component: data-science-pipelines
        dspa: pipelines-definition
    spec:
      restartPolicy: Always
      serviceAccountName: ds-pipelines-mariadb-sa-pipelines-definition
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 800Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  MYSQL_PWD=$MYSQL_PASSWORD mysql -h 127.0.0.1 -u $MYSQL_USER -D
                  $MYSQL_DATABASE -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: mariadb
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MYSQL_USER
              value: mlpipeline
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ds-pipeline-db-pipelines-definition
                  key: password
            - name: MYSQL_DATABASE
              value: mlpipeline
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'true'
          ports:
            - containerPort: 3306
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
          terminationMessagePolicy: File
          image: >-
            registry.redhat.io/rhel8/mariadb-103@sha256:b3a6f3fecc2629b61a8940e792e623318c46fd71585486794f6cebb76c89b5df
      serviceAccount: ds-pipelines-mariadb-sa-pipelines-definition
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pipelines-definition
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2024-02-14T18:50:42Z'
      lastTransitionTime: '2024-02-14T18:50:42Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2024-02-14T18:50:42Z'
      lastTransitionTime: '2024-02-14T18:49:42Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "mariadb-pipelines-definition-594fb6d4" has successfully
        progressed.
