kind: Service
apiVersion: v1
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: model-serving-proxy-tls
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1687181228
    service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1687181228
  resourceVersion: '484222478'
  name: modelmesh-serving
  uid: 6c5d5de7-f997-4b6f-950d-21f16321cbbd
  creationTimestamp: '2024-02-23T14:14:36Z'
  managedFields:
    - manager: manager
      operation: Update
      apiVersion: v1
      time: '2024-02-23T14:14:36Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:service.alpha.openshift.io/serving-cert-secret-name': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:modelmesh-service': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"33445ba3-d903-45ec-b293-20e3a77e3f68"}': {}
        'f:spec':
          'f:clusterIP': {}
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":2112,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            'k:{"port":8008,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            'k:{"port":8033,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            'k:{"port":8443,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
    - manager: service-ca-operator
      operation: Update
      apiVersion: v1
      time: '2024-02-23T14:14:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:service.alpha.openshift.io/serving-cert-signed-by': {}
            'f:service.beta.openshift.io/serving-cert-signed-by': {}
  namespace: fraud-detection-w-modelmesh
  ownerReferences:
    - apiVersion: v1
      kind: Namespace
      name: fraud-detection-w-modelmesh
      uid: 33445ba3-d903-45ec-b293-20e3a77e3f68
      controller: true
      blockOwnerDeletion: true
  labels:
    app.kubernetes.io/instance: modelmesh-controller
    app.kubernetes.io/managed-by: modelmesh-controller
    app.kubernetes.io/name: modelmesh-controller
    modelmesh-service: modelmesh-serving
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: grpc
      protocol: TCP
      port: 8033
      targetPort: grpc
    - name: http
      protocol: TCP
      port: 8008
      targetPort: http
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
    - name: prometheus
      protocol: TCP
      port: 2112
      targetPort: prometheus
  internalTrafficPolicy: Cluster
  clusterIPs:
    - None
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    modelmesh-service: modelmesh-serving
status:
  loadBalancer: {}
