apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: fraud
    serving.kserve.io/deploymentMode: ModelMesh
  name: fraud
  namespace: fraud-detection-w-modelmesh
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: '1'
      name: ''
      resources: {}
      runtime: triton
      storage:
        key: aws-connection-my-storage
        path: models/fraud
