apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: ''
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: OpenVINO Model Server
    opendatahub.io/template-name: ovms
    openshift.io/display-name: OVMS
  resourceVersion: '484231453'
  name: ovms
  uid: 4f7c5514-2a1f-479b-9978-93ffe4170856
  creationTimestamp: '2024-02-23T14:19:21Z'
  generation: 1
  managedFields:
    - apiVersion: serving.kserve.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:opendatahub.io/accelerator-name': {}
            'f:opendatahub.io/recommended-accelerators': {}
            'f:opendatahub.io/template-display-name': {}
            'f:opendatahub.io/template-name': {}
            'f:openshift.io/display-name': {}
          'f:labels':
            .: {}
            'f:opendatahub.io/dashboard': {}
        'f:spec':
          'f:builtInAdapter':
            .: {}
            'f:env': {}
            'f:memBufferBytes': {}
            'f:modelLoadingTimeoutMillis': {}
            'f:runtimeManagementPort': {}
            'f:serverType': {}
          'f:multiModel': {}
          'f:volumes': {}
          'f:containers': {}
          'f:protocolVersions': {}
          'f:grpcEndpoint': {}
          'f:tolerations': {}
          'f:supportedModelFormats': {}
          .: {}
          'f:replicas': {}
          'f:grpcDataEndpoint': {}
      manager: unknown
      operation: Update
      time: '2024-02-23T14:19:21Z'
  namespace: fraud-detection-w-modelmesh
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  supportedModelFormats:
    - autoSelect: true
      name: openvino_ir
      version: opset1
    - autoSelect: true
      name: onnx
      version: '1'
    - autoSelect: true
      name: tensorflow
      version: '2'
  builtInAdapter:
    env:
      - name: OVMS_FORCE_TARGET_DEVICE
        value: AUTO
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
    runtimeManagementPort: 8888
    serverType: ovms
  multiModel: true
  containers:
    - args:
        - '--port=8001'
        - '--rest_port=8888'
        - '--config_path=/models/model_config_list.json'
        - '--file_system_poll_wait_seconds=0'
        - '--grpc_bind_address=127.0.0.1'
        - '--rest_bind_address=127.0.0.1'
      image: >-
        quay.io/modh/openvino_model_server@sha256:007304a96acd654ca5133c50990c6785464fcea44304c8a846d3279b9c83a9d4
      name: ovms
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  protocolVersions:
    - grpc-v1
  grpcEndpoint: 'port:8085'
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
  replicas: 1
  tolerations: []
  grpcDataEndpoint: 'port:8001'
