kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-my-storage
  namespace: fraud-detection
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: My Storage
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_DEFAULT_REGION: ""
  AWS_S3_BUCKET: ""
  AWS_S3_ENDPOINT: ""
  AWS_SECRET_ACCESS_KEY: ""
type: Opaque
