kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.first: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"fraud-detection"}}
  name: fraud-detection
  namespace: fraud-detection
  ownerReferences:
    - apiVersion: kubeflow.org/v1
      kind: Notebook
      name: fraud-detection
      uid: 97117d0b-355a-4dc5-b20f-a6e2ea26d074
      controller: true
      blockOwnerDeletion: true
  labels:
    notebook-name: fraud-detection
secrets:
  - name: fraud-detection-dockercfg-n4hk2
imagePullSecrets:
  - name: fraud-detection-dockercfg-n4hk2
